### PR TITLE
Run debt ceiling at exit during test suite, define modest ceiling

### PR DESCRIPTION
**Pull request by bglusman**
Here you go, see how you like this :-)

### CODE REVIEW

**Comment by karlhigley** [comment]
This seems like good feedback, but I probably don't need to see the technical debt info every time I run the specs (e.g. with Guard). Could it be configured to run as part of an optional comprehensive test suite or on Travis only?

**Comment by bglusman** [comment]
Sure, would you want it to default to on or off I guess?  I have an ENV variable skip I used on debt ceiling itself as `SKIP=true rspec` to not run, that would be easy to throw into Guard so its not run that way, but is run every time you run form CI or by explicity calling rspec...  just throw into the rspec_helper `unless ENV['SKIP']`, or I can.  I don't know if theres an easy way I could integrate that into debt_ceiling itself, though maybe for a few specific environments there's some metadata/etc I could reflect on if a config option is present?  Dunno...

**Comment by bglusman** [comment]
Oh I guess could add a config option for default full info every time, full
info only on failure or (maybe?) default silent failure, than have explicit
command flags for eqch mode also?  Yeah that seems like a good idea, I'll
make a ticket in waffle.io (which uses gh tickets, nice system for
opensource kanban etc)

On Wednesday, December 30, 2015, Karl Higley notifications@github.com
wrote:

> This seems like good feedback, but I probably don't need to see the
> technical debt info every time I run the specs (e.g. with Guard). Could it
> be configured to run as part of an optional comprehensive test suite or on
> Travis only?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/karlhigley/alder/pull/1#issuecomment-168097468.

## 
- Brian

**Comment by karlhigley** [comment]
My main concern with evaluating debt every time the specs run is that it introduces a short but noticeable delay at the end of the spec runs. That's not much of a problem for manual runs, but it would be a hiccup with Guard. On the other hand, though, I haven't set up Guard yet, so that's probably not a reason to hold off on merging this.

**Comment by karlhigley** [comment]
(Just needs a rebase.)

**Pull request closed without merging**
